### ISSUE TITLE
parser barfs on enums with large values

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#35]
I have a model containing an enum like this:

```
    type enumeration {
      enum foo                       { value 2038431744; }
    }
```

But the parser doesn't like it:

```
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 34, in <module>
    yf = yin_model.CPSYangModel(d)
  File "/usr/lib/opx/py/yin_model.py", line 163, in __init__
    _modules_[plugin].write()
  File "/usr/lib/opx/py/cps_c_lang.py", line 235, in write
    self.write_details('header')
  File "/usr/lib/opx/py/cps_c_lang.py", line 243, in write_details
    class_type.COutputFormat(self.context).show(self.model)
  File "/usr/lib/opx/py/cps_h.py", line 338, in show
    self.print_enums(model)
  File "/usr/lib/opx/py/cps_h.py", line 108, in print_enums
    self.show_enum(model,i)
  File "/usr/lib/opx/py/cps_h.py", line 80, in show_enum
    value = str(history.get_enum(en_name, value, parent=name))
  File "/usr/lib/opx/py/object_history.py", line 217, in get_enum
    res = self.the_dict[parent].get_value(name, requested)
  File "/usr/lib/opx/py/object_history.py", line 46, in get_value
    self.add_enum(name, ix)
  File "/usr/lib/opx/py/object_history.py", line 32, in add_enum
    raise Exception("Invalid id detected " + str(index))
Exception: Invalid id detected 2038431744
```

... per [this line](https://github.com/open-switch/opx-cps/blob/554c317ccbef3890acfb2d5fb9b0474517f7ed8d/scripts/lib/yang_tools/py/object_history.py#L31).

So far as I can see the large value is valid: RFC6020 9.6.4.2 says:

> The "value" statement, which is optional, is used to associate an integer value with the assigned name for the enum.  This integer value MUST be in the range -2147483648 to 2147483647 ...

Can the parser be persuaded to tolerate a wider range of values?

**Comment by c-wichmann** [comment]
Will patch it in the next update.  If you need it earlier, let me know.

**Comment by c-wichmann** [comment]
This is resolved internally - separated the enum processing from the derived objects and fixed up some of the history logic at the same time.

**Comment by c-wichmann** [comment]
Code was synced and this issue is now resolved.
