### ISSUE TITLE
CPS doesn't store interface description

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-cps#49]
`if/interfaces/interface/description` is in `ietf-interface.yang` and imported unchanged by the interfaces `dell-base-if` model, but the description field doesn't appear to be stored or returned by CPS:
```
opxUser@opx_vm:~$ sudo cps_get_oid.py target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-001-0

Key: 1.19.44.2883617.2883612.2883613.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 11
dell-if/if/interfaces/interface/phys-address = 08:00:27:ce:9a:c6
dell-if/if/interfaces/interface/speed = 6
base-if-phy/if/interfaces/interface/learn-mode = 3
if/interfaces/interface/name = e101-001-0
dell-if/if/interfaces/interface/duplex = 1
dell-if/if/interfaces/interface/auto-negotiation = 0
if/interfaces/interface/type = ianaift:ethernetCsmacd
dell-if/if/interfaces/interface/fec = 2
dell-if/if/interfaces/interface/oui = 6976381
base-if-phy/if/interfaces/interface/port-id = 25
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 1
base-if-phy/if/interfaces/interface/tagging-mode = 3

opxUser@opx_vm:~$ sudo cps_get_oid.py target dell-base-if-cmn/if/interfaces/interface/description if/interfaces/interface/name=e101-001-0
Traceback (most recent call last):
  File "/usr/bin/cps_get_oid.py", line 41, in <module>
    cur_obj = cps_object.CPSObject(qual=qual,module=e)
  File "/usr/lib/opx/cps_object.py", line 73, in __init__
    "Invalid Module Name or object doesn't have the key")
ValueError: Invalid Module Name or object doesn't have the key

```

**Comment by mcallisterjp** [comment]
Actually, looks like this is a dupe of #41. Sorry about that.

**Comment by peterbrittain** [comment]
Actually, with #41 we agreed not to implement descriptions, so this should be re-opened.  Can you please do that?

**Comment by atanu-mandal** [comment]
Reopening this to provide "description" attribute.

**Comment by jeff-yin** [comment]
The design for this is currently being discussed -- whether to put the interface description in the CPS DB or whether to store it in some existing data structure. Targeting 3/8 for closure.

**Comment by atanu-mandal** [comment]
Fixes are in review
https://review.openswitch.net/#/c/14574/
https://review.openswitch.net/#/c/14573/

**Comment by atanu-mandal** [comment]
Fix is merged. Currently "description" is properly populated for all the interfaces (physical, LAG, VLAN) except loopback interface. Hope I can close this issue now. Please reopen if needed.
