### ISSUE TITLE
opx-config-switch show command is failing.

### ISSUE THREAD

**Issue by pyadvichuk** [open-switch/opx-cps#60]
`opx-config-switch` show not working and gives traceback 

For my understanding current traceback relates to the `/usr/lib/opx/cps_utils.py` as the `bytearray_utils` function can't print values of type `leaf-list` and failure happened when it tried to print
`leaf-list supported-profiles` from `switch.xml`
 

```
root@OPX:/home/admin# opx-config-switch set switch-id=0 mac-age-timer=120
Success

root@OPX:/home/admin# opx-config-switch show
Key: 1.36.2359341.
base-switch/switching-entities/switch-count = 1
Key: 1.36.2359341.2359299.2359302.
base-switch/switching-entities/switching-entity/num-unicast-queues-per-port = 16
base-switch/switching-entities/switching-entity/acl-entry-max-priority = 512
base-switch/switching-entities/switching-entity/bridge-table-size = 65536
base-switch/switching-entities/switching-entity/max-ecmp-entry-per-group = 0
base-switch/switching-entities/switching-entity/ecmp-hash-algorithm = 2
Traceback (most recent call last):
  File "/usr/bin/opx-config-switch", line 55, in <module>
    options[opt](sys.argv[2:])
  File "/usr/bin/opx-config-switch", line 22, in show_switch
    nas_switch_utils.show_switch(args)
  File "/usr/lib/x86_64-linux-gnu/opx/nas_switch_utils.py", line 58, in show_switch
    cps_utils.print_obj
  File "/usr/lib/opx/cps_utils.py", line 293, in print_obj
    cps_attr_types_map.print_object(obj, log=None)
  File "/usr/lib/opx/cps_utils.py", line 187, in print_object
    print_methods[module](data)
  File "/usr/lib/x86_64-linux-gnu/opx/nas_switch_utils.py", line 65, in print_switch_details
    value = cps_object.types.from_data(key,data)
  File "/usr/lib/opx/cps_utils.py", line 148, in from_data
    return bytearray_utils.ba_to_value(t, val)
  File "/usr/lib/opx/bytearray_utils.py", line 259, in ba_to_value
    return ba_to_type[typ](typ, val)
  File "/usr/lib/opx/bytearray_utils.py", line 199, in ba_to_str_wr
    return ba_to_str(val, len(val))
  File "/usr/lib/opx/bytearray_utils.py", line 125, in ba_to_str
    s = struct.unpack('<' + str(length) + 's', ba[0:length])[0]
struct.error: unpack requires a string argument of length 1
root@OPX:/home/admin#
```

**Comment by atanu-mandal** [comment]
With OPX 2.2.0 I have tried the same , it seems to be working fine. 

Is the configuration applied properly to the NPU?

OPX 2.2.0 Log:

root@OPX:~# opx-config-switch show
Key: 1.36.2359341.
base-switch/switching-entities/switch-count = 1
Key: 1.36.2359341.2359299.2359302.
base-switch/switching-entities/switching-entity/num-unicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/uft-mode = 1
base-switch/switching-entities/switching-entity/lag-hash-algorithm = 2
base-switch/switching-entities/switching-entity/acl-entry-max-priority = 2147483647
base-switch/switching-entities/switching-entity/bridge-table-size = 163840
base-switch/switching-entities/switching-entity/max-ecmp-entry-per-group = 0
base-switch/switching-entities/switching-entity/ecmp-hash-algorithm = 2
base-switch/switching-entities/switching-entity/lag-hash-seed-value = 0
base-switch/switching-entities/switching-entity/ingress-buffer-pool-num = 4
base-switch/switching-entities/switching-entity/acl-table-max-priority = 11
base-switch/switching-entities/switching-entity/acl-table-min-priority = 0
base-switch/switching-entities/switching-entity/max-mtu = 9216
base-switch/switching-entities/switching-entity/acl-entry-min-priority = 0
base-switch/switching-entities/switching-entity/counter-refresh-interval = 5
base-switch/switching-entities/switching-entity/num-queues-per-port = 20
base-switch/switching-entities/switching-entity/total-buffer-size = 12188
base-switch/switching-entities/switching-entity/mac-age-timer = 1800
base-switch/switching-entities/switching-entity/egress-buffer-pool-num = 4
base-switch/switching-entities/switching-entity/num-multicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/default-mac-address = 90:b1:1c:f4:9a:f5
base-switch/switching-entities/switching-entity/num-queues-cpu-port = 43
base-switch/switching-entities/switching-entity/uft-mode-info/l2-mac-table-size = 163840
base-switch/switching-entities/switching-entity/uft-mode-info/host-table-size = 147456
base-switch/switching-entities/switching-entity/uft-mode-info/mode = 1
base-switch/switching-entities/switching-entity/uft-mode-info/l3-route-table-size = 16384
base-switch/switching-entities/switching-entity/switch-id = 0
base-switch/switching-entities/switching-entity/temperature = 43
base-switch/switching-entities/switching-entity/switch-mode = store-and-forward (2)
base-switch/switching-entities/switching-entity/ecmp-hash-seed-value = 0

root@OPX:~# opx-config-switch set switch-id=0 mac-age-timer=120
Success

root@OPX:~# opx-config-switch show
Key: 1.36.2359341.
base-switch/switching-entities/switch-count = 1
Key: 1.36.2359341.2359299.2359302.
base-switch/switching-entities/switching-entity/num-unicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/uft-mode = 1
base-switch/switching-entities/switching-entity/lag-hash-algorithm = 2
base-switch/switching-entities/switching-entity/acl-entry-max-priority = 2147483647
base-switch/switching-entities/switching-entity/bridge-table-size = 163840
base-switch/switching-entities/switching-entity/max-ecmp-entry-per-group = 0
base-switch/switching-entities/switching-entity/ecmp-hash-algorithm = 2
base-switch/switching-entities/switching-entity/lag-hash-seed-value = 0
base-switch/switching-entities/switching-entity/ingress-buffer-pool-num = 4
base-switch/switching-entities/switching-entity/acl-table-max-priority = 11
base-switch/switching-entities/switching-entity/acl-table-min-priority = 0
base-switch/switching-entities/switching-entity/max-mtu = 9216
base-switch/switching-entities/switching-entity/acl-entry-min-priority = 0
base-switch/switching-entities/switching-entity/counter-refresh-interval = 5
base-switch/switching-entities/switching-entity/num-queues-per-port = 20
base-switch/switching-entities/switching-entity/total-buffer-size = 12188
base-switch/switching-entities/switching-entity/mac-age-timer = 120
base-switch/switching-entities/switching-entity/egress-buffer-pool-num = 4
base-switch/switching-entities/switching-entity/num-multicast-queues-per-port = 10
base-switch/switching-entities/switching-entity/default-mac-address = 90:b1:1c:f4:9a:f5
base-switch/switching-entities/switching-entity/num-queues-cpu-port = 43
base-switch/switching-entities/switching-entity/uft-mode-info/l2-mac-table-size = 163840
base-switch/switching-entities/switching-entity/uft-mode-info/host-table-size = 147456
base-switch/switching-entities/switching-entity/uft-mode-info/mode = 1
base-switch/switching-entities/switching-entity/uft-mode-info/l3-route-table-size = 16384
base-switch/switching-entities/switching-entity/switch-id = 0
base-switch/switching-entities/switching-entity/temperature = 43
base-switch/switching-entities/switching-entity/switch-mode = store-and-forward (2)
base-switch/switching-entities/switching-entity/ecmp-hash-seed-value = 0

**Comment by pyadvichuk** [comment]
From my understanding, you are not using "switch_profile" tag in the switch.xml. Just try to add 
to switch.xml.

<switch_profile default_profile="default">
                        <entry supported_profile="default"/>
                        <entry supported_profile="routing"/>
</switch_profile>

I've made a simple fix for this. Is it suitable to open the PR on git.openswitch.net?

**Comment by hpersh** [comment]
@pyadvichuk   I'm not sure what you are asking...  The config file /etc/opx/switch.xml is platform-dependent... and you are creating the config files for the AS7512-32X platform...  no?

**Comment by jeff-yin** [comment]
@pyadvichuk any update?
