### ISSUE TITLE
opx-base-model fails to build due to problem in yin_utils.py

### ISSUE THREAD

**Issue by danielginsburg** [open-switch/opx-cps#95]
When doing a clean build opx-base-model fails:

...
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 36, in <module>
    with yin_model.CPSYangModel(d) as yf:    
  File "/usr/lib/opx/py/yin_model.py", line 127, in __init__
    self.model = self.context['loader'].load(self.filename)
  File "/usr/lib/opx/py/yin_model.py", line 94, in load
    return self.get_parsed_yin(yang_file, prefix)
  File "/usr/lib/opx/py/yin_model.py", line 78, in get_parsed_yin
    _model.load(prefix=prefix)
  File "/usr/lib/opx/py/yin_cps.py", line 124, in load
    self.context.get_yang_nodes(self.filename))
  File "/usr/lib/opx/py/cps_context.py", line 141, in get_yang_nodes
    _oas_file = self.__details['openapi-spec'].get_openapi_file(yang_file)
  File "/usr/lib/opx/py/yin_utils.py", line 85, in get_openapi_file
    self.mkdirOas(),
  File "/usr/lib/opx/py/yin_utils.py", line 62, in mkdirOas
    p = subprocess.Popen(['ar_tool.py','sysroot'],stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
..

Indeed, the most recent commit touching scripts/lib/yang_tools/py/yin_utils.py introduced a popen of "ar_tool.py" which is nowhere to be found in any opx-* repo.

**Comment by jeff-yin** [comment]
Should be fixed by most recent commit in opx-cps.
